# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jongmin Lee
title: Backend & Devops Engineer
email: dumptruck60@naver.com
website: www.github.com/coys-lee

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  coys-lee
linkedin_username: jongmin-lee-984672208

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jongmin Lee and I'm a Backend & Devops. As well as developing web, I am also good at communicating with people. I have worked at Samsung Electronic(S.LSI) gaining teamwork and leadership skills.

  I am most skilled in: <mark>Python</mark> and <mark>Docker</mark>

content:
  - title: Backend Engineer # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        image: images/profile.jpg
        # link_text: Project Website
        description: | 
          I developed the portal backend provided to engineers through <mark>python</mark>, <mark>graphql</mark>, and <mark>sqlalchemy</mark>, and used all of <mark>mongodb</mark>, <mark>postgresql</mark>, and <mark>oracledb</mark>.
          Also, I developed a real-time server that can interface with an external server,  with a file base and API base (JSON).
          I have learned many skills through this and been I'm very proud of having this in my portfolio.

  - title: Devops Engineer
    layout: list # Type of content section (list/text)
    content:
      - layout: left
      image: images/monitoring.jpg
        description: | 
            I have built an environment in which <mark>Docker</mark> is created and operated based on container when developers do git push/merge.
            Also, using <mark>metrics, <mark>loki</mark>, <mark>prometheus</mark>, and <mark>grafana</mark>, I have established a real-time monitoring environment for operating services, and a mailing service using <mark>restapi</mark> and <mark>smtp</mark> when a problem occurred.
            Currently, I am building <mark>kubernetes</mark> for managing a large number of servers and for service stability.
  
# Footer
footer_show_references: true
# references_title: Nice to meet you (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
